services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://125.20.54.14:5555
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app
      - ./backend/firebase-credentials.json:/app/firebase-credentials.json:ro
    environment:
      - FLASK_APP=beergame
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-credentials.json
